### ISSUE TITLE
Security Compliance Issue for [SFI-ES5.1] Azure Artifacts - Central Feed Services (CFS)

### ISSUE THREAD

**Issue by Xieyan** [microsoft/security-devops-action#111]
Hi Team,

I integrated this tool into our repo build pipeline, but encountered a security compliance issue [SFI-ES5.1] related to Azure Artifacts - Central Feed Services (CFS). The requirement is that builds must pull open-source libraries from an [Azure Artifacts] feed. But currently, MSDO is pulling from a open source feed.

```
GET https://msdous.pkgs.visualstudio.com/d1ee6cdc-c4ce-4e34-95df-4c038f0d3683/_packaging/7c44b921-ee7b-48f1-bad3-d9227399a9fc/nuget/v3/registrations2-semver2/microsoft.security.devops.tools.configuration/index.json
```

Should we consider supporting a feed suppression feature to help meet **security** compliance requirements?

Thanks,
Best regards,

**Comment by reynoldsa** [comment]
This is an azure artifacts feed. I would take it up with whatever security scanner is setting off.
