### ISSUE TITLE
Disabling binskim?

### ISSUE THREAD

**Issue by ahmedsza** [microsoft/security-devops-action#28]
I am trying this action out against the OWASP juice app
When I run the action i get errors like this

BINSKIM : error ERR997.NoValidAnalysisTargets : No valid analysis targets were specified.
    
    Analysis did not complete due to one or more unrecoverable execution conditions.
    Unexpected fatal runtime condition(s) observed: NoValidAnalysisTargets
    
    Tool run time: 0.9085511 seconds
    ------------------------------------------------------------------------------
    BinSkim completed with exit code 1
Error:      Error running binskim job: 13 of 67
Error:      GuardianErrorExitCodeException: binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir/*.dll, or dir/*

is there an easy way to turn this off - or to just ignore this?

**Comment by chrisnielsen-MS** [comment]
You can update your action definition according using the inputs in the action.yml file. You can use either the tools or categories inputs to limit which tools run.
