### ISSUE TITLE
Use of the deprecated Node.js 12 image

### ISSUE THREAD

**Issue by JohnnyB85** [microsoft/security-devops-action#29]
The action.yml file uses a deprecated Node.js 12 image which no longer receices any kind of security updates:

https://nodejs.org/en/blog/release/v12.22.12/

Please upgrade it to a higher supported version.

**Comment by davidknise** [comment]
Thanks for reporting this. It appears to have been fixed on Oct 27th, 2022:
https://github.com/microsoft/security-devops-action/commit/e94440350ed10e2806d47cd0d7504a2c51abdbe9#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6
