### ISSUE TITLE
Error when running the task Microsoft Security DevOps in YAML Pipeline

### ISSUE THREAD

**Issue by ouaesjamali** [microsoft/security-devops-action#34]
While testing out the Microsoft Security DevOps extension, we are getting the error 
**GuardianErrorExitCodeException: templateanalyzer completed with an Error exit code: 22. Violation + Error: Scan encountered both violations in template(s) and errors trying to analyze template(s)**

The YAML pipeline code is 
```trigger: none
pool:
  vmImage: 'windows-latest'
steps:
- task: UseDotNet@2
  displayName: 'Use dotnet'
  inputs:
    version: 3.1.x
- task: UseDotNet@2
  displayName: 'Use dotnet'
  inputs:
    version: 5.0.x
- task: UseDotNet@2
  displayName: 'Use dotnet'
  inputs:
    version: 6.0.x
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
    categories: 'IaC'
```
Attaching the logs from the build for reference.
[logs_325.zip](https://github.com/microsoft/security-devops-action/files/9975275/logs_325.zip)

**Comment by chrisnielsen-MS** [comment]
It looks like according to the logs, some of the template files that were scanned could not be parsed:
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: {.

Unfortunately, the logs do not tell us which file this was. Please validate the template files in your source and try again.
