### ISSUE TITLE
Specify IaC type when we use terrascan

### ISSUE THREAD

**Issue by vidal777** [microsoft/security-devops-action#82]
Basically, it's possible to specify iac types when we use terrascan tool? The thing is that terrascan automatically detects the diferents types based on the files. On a kustomize applying patch on diferents environments, terrascan detect k8s deployment and print some high vulnerability but in reality on the main deployment are resolved.

**Comment by boAndron** [comment]
Hello!
Please check out our documentation on how to configure MSDO and the tools [here](https://github.com/microsoft/security-devops-action/wiki )
You can set a build / environment variable called GDN_TERRASCAN_IACTYPE to configure the setting you asked about.
Thanks!
