### ISSUE TITLE
Update action to use Node v20

### ISSUE THREAD

**Issue by c-ryan-k** [microsoft/security-devops-action#89]
Node 16 actions are being deprecated by Github and we're starting to get warnings in our workflows:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jb-leic** [comment]
is there an ETA on this?

**Comment by c-ryan-k** [comment]
@sethRait any updates on this? Is this tool still supported?

**Comment by chrisnielsen-MS** [comment]
This update was merged in today.
