### ISSUE TITLE
Question: Does this action feedback to MS / have any impact on Windows Defender SmartScreen?

### ISSUE THREAD

**Issue by JohnLBevan** [microsoft/security-devops-action#94]
When sharing executables of our apps SmartScreen blocks users from running the app with a warning (unless the user opens the file properties and selects `Unblock`).

Per this [StackOverflow Post](https://stackoverflow.com/a/66582477/361842) files can be submitted to MS for analysis at [https://www.microsoft.com/en-us/wdsi/filesubmission](https://www.microsoft.com/en-us/wdsi/filesubmission) which can cause the SmartScreen DB to be updated to recognise the app as safe.

It would be great if we could build this submission into our pipelines, rather than developers having to download the produced output and manually upload it to MS.
Does this GitHub action also feedback to MS so as to update the SmartScreen database?
If not, is there an equivalent action which does?  I believe MS require that we use an organisation account when submitting files via the above site; but perhaps GH Actions could use a Service Principal from our MS Entra account (or something similar) for this?

**Comment by charlesoxyer** [comment]
Hi @JohnLBevan, the MSDO action does not currently support exemption submissions to the SmartScreen DB. I am not aware of an MS supported tool that has this capability. However, I have noted the feature request and we will continuously monitor the demand for such a capability and prioritize accordingly.
